import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.ts', 'src/cli/index.ts'],
  format: ['cjs', 'esm'],
  dts: true,
  sourcemap: true,
  clean: true,
  target: 'es2020',
  onSuccess: 'node scripts/generate-bin.mjs',
  treeshake: true,
  external: [
    // 第三方库
    'glob',
    'commander',
    'chalk',
    'chokidar',
    'lodash',
    'micromatch',
    'fs-extra',
    'inquirer',
    'listr2',
    'console-table-printer',
    'cli-table3',
    'ora',
    'ts-morph',
    // Node.js 内置模块
    'fs',
    'path',
    'os',
    'util',
    'events',
    'child_process',
    'crypto',
    'stream',
    'buffer',
    'readline',
    'zlib',
    'http',
    'https',
    'url',
    'querystring',
    'net',
    'tls',
    'dns',
    'assert',
  ],
});
